name: Trigger auto deployment for recipegenerator-ingredient

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/recipegenerator-ingredient-AutoDeployTrigger-72f2c15d-4fab-4d76-a8d5-3f15aedb5f03.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Specify the Java version you need
          distribution: 'adopt'

      - name: Run unit tests with Maven
        run: mvn test -DskipITs=true

      - name: Run integration tests with Maven
        run: mvn -Dskip.ut=true verify

      - name: Compile code with Maven
        run: mvn package -DskipTests

      - name: Run SonarCloud code analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=saprone
            -Dsonar.projectKey=Saprone_Ingredient
            -Dsonar.java.binaries=target/classes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud quality gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud quality gate status
        run: echo "The quality gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECIPEGENERATORINGREDIENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPEGENERATORINGREDIENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPEGENERATORINGREDIENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to Docker Hub
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RECIPEGENERATORINGREDIENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECIPEGENERATORINGREDIENT_REGISTRY_PASSWORD }}
          containerAppName: recipegenerator-ingredient
          resourceGroup: saprone-resource-group
          imageToBuild: saprone/recipegenerator-ingredient:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


